### ISSUE TITLE
Video/Audio Sync after hours of playback

### ISSUE THREAD

**Issue by prwaves** [jwplayer/jw-showcase-appletv#40]
The app works great, however after streaming JW Player hosted videos for several hours, we are having issues with the video freezing and the audio continuing and not synching back up. This only occurs after a significant amount of time. For example, users are expecting to keep the videos streaming for about 8 hours or more. Is anyone else having a similar issue?

**Comment by johnluther** [comment]
Hi, Peter. Thanks for bringing this to our attention. I haven't seen it myself.

Can you provide us with a sample HLS stream so we can test? 

JL

**Comment by prwaves** [comment]
John, here's a sample stream that I'm using: [https://content.jwplatform.com/feeds/IkoZxGTB.rss](url)

**Comment by johnluther** [comment]
@prwaves , are you still seeing this issue?
