### ISSUE TITLE
HomeScreen Playlist Not Updating 

### ISSUE THREAD

**Issue by angusykl** [jwplayer/jw-showcase-appletv#52]
Hi Guys, 

Thanks for the awesome work! 

However, I have found that the AppleTV will not update automatically when users go back to the home screen. Unlike mobile devices, the tvos app will not exit without users' request. Is there any ways for me to automatically update the playlist every time user goes back to the home screen? 

Do you guys have any tips for me to achieve this? 

Thanks!

**Comment by johnluther** [comment]
Thanks, @angusykl . 

@RikHeijdens , I thought we fixed this in https://github.com/jwplayer/jw-showcase-appletv/pull/37?

**Comment by angusykl** [comment]
Thanks John!

I just realized that I was using the old version.
