### ISSUE TITLE
Dynamic Playlist

### ISSUE THREAD

**Issue by vjxplicit** [jwplayer/jw-showcase-appletv#53]
Anyone else have issue with dynamic playlist. getting this error:

jwplayer-for-tv[8831:1172330] ITML <Error>: Unsupported tag [div]

Anyway to get dynamic playlist to work?

**Comment by RikHeijdens** [comment]
Thanks for this. We're working on a fix.

As for now, you can workaround this by making sure that a Poster Image has been set for your media.

**Comment by RikHeijdens** [comment]
This has been fixed in version [1.0.2](https://github.com/jwplayer/jw-showcase-appletv/releases/tag/1.0.2). If you're using the "current" endpoint this will be fixed automatically, please let me know if you experience any other issues.

**Comment by vjxplicit** [comment]
This update does not seem to have fixed my issue. Even when all our media within the playlist have artwork it does not show a dynamic playlist. if i create a static playlist with same media manually attached it works fine. 

Any suggestions?

**Comment by RikHeijdens** [comment]
Could you send me the identifier of the playlist?

**Comment by vjxplicit** [comment]
@RikHeijdens mKeT6eFS

**Comment by RikHeijdens** [comment]
I've downloaded your playlist and it looks like this:

```json
{
    "playlist": [{
        "description": "Coming Soon",
        "pubdate": 1473675753,
        "tags": "oldschool",
        "image": "//content.jwplatform.com/thumbs/VROY1oJ4-720.jpg",
        "sources": [{
            "type": "video/mp4",
            "file": "https://vimeo.com/102797653"
        }],
        "tracks": [],
        "link": "//content.jwplatform.com/previews/VROY1oJ4",
        "duration": 0,
        "mediaid": "VROY1oJ4",
        "title": "Old School | Classics",
        "custom": {}
    }, {
        "description": "Rock, Pop & Nu~Wave",
        "pubdate": 1473680400,
        "tags": "Coming Soon,classics,oldschool",
        "image": "//content.jwplatform.com/thumbs/MvkPXYb3-720.jpg",
        "sources": [{
            "type": "video/mp4",
            "file": "https://vimeo.com/111315356"
        }],
        "tracks": [],
        "link": "//content.jwplatform.com/previews/MvkPXYb3",
        "duration": 0,
        "mediaid": "MvkPXYb3",
        "title": "80\u2019s Party Mix",
        "custom": {}
    }],
    "title": "Oldschool | Classics",
    "kind": "dynamic",
    "feedid": "mKeT6eFS"
}
```

As you can see the sources array contains a link to vimeo. This is incorrect, the `file` key in the sources object must point directly to a media file or stream.

The easiest way to solve this is to remove the videos with vimeo urls that do not point directly to media from your account. After you did you can upload the videos through our dashboard to your account and then the dynamic playlists should work for Apple TV.

**Comment by vjxplicit** [comment]
Will this work with hosted files within s3 bucket??

Get Outlook for Android



On Sat, Sep 17, 2016 at 4:57 AM +1200, "Rik Heijdens" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #53<https://github.com/jwplayer/jw-showcase-appletv/issues/53>.

-

**Comment by RikHeijdens** [comment]
Yes, it will, as long as you provide a URL that directly links to the media.

**Comment by vjxplicit** [comment]
so no frontcloud support yet?

**Comment by vjxplicit** [comment]
can you check that playlist again. i have set it up with an rtmp link but still not showing anything.

**Comment by RikHeijdens** [comment]
RTMP is not supported on Apple TV.

You need to link directly to a MP4 file or HLS stream.

**Comment by vjxplicit** [comment]
Thanks for all your help. I really dont know what im doing wrong but just cant seem to get even direct files to work.

UaZ8FKwu - playlist that doesnt work.
iZTDPPUd - playlist that has 2/3 files that work.

**Comment by RikHeijdens** [comment]
I've checked your playlists:

- `UaZ8FKwu`: Doesn't work because none of the playlist items contains an HLS stream, at this moment we only support HLS playback. If you want to change that behavior you should take a look at our [PlaylistLoader](https://github.com/jwplayer/jw-showcase-appletv/blob/master/jwplayer-appletv-web-app/js/playlist/PlaylistLoader.js#L99) and modify it so that it uses MP4 streams.
- `iZTDPPUd`: Only 2 of the 3 items work, because they contain HLS streams.

Most likely you just want to add HLS streams from Vimeo for every playlist item, that will solve your issue.

**Comment by vjxplicit** [comment]
O I thought it could play mp4 or HLS

Get Outlook for Android



On Mon, Sep 19, 2016 at 2:45 AM +1200, "Rik Heijdens" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've checked your playlists:

  *   UaZ8FKwu: Doesn't work because none of the playlist items contains an HLS stream, at this moment we only support HLS playback. If you want to change that behavior you should take a look at our PlaylistLoader<https://github.com/jwplayer/jw-showcase-appletv/blob/master/jwplayer-appletv-web-app/js/playlist/PlaylistLoader.js#L99> and modify it so that it uses MP4 streams.
  *   iZTDPPUd: Only 2 of the 3 items work, because they contain HLS streams.

Most likely you just want to add HLS streams from Vimeo for every playlist item, that will solve your issue.

-
