### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by cesarcarlos75** [jwplayer/jw-showcase-appletv#65]
I've been testing the showcase app and I've noticed that even though our videos are encoded for different qualities, including 1080, videos loaded into the app (when watched in the simulator) always appear in a low quality. Is there a setting that can be modified? Or does this depend on bandwidth? I'm watching the same video in a web player (using JW) and the quality is HiRes.
Thanks.

**Comment by RikHeijdens** [comment]
I've noticed this too - I'm not sure what causes this but I believe it started happening after I updated either my Simulator or XCode.

Playback should be fine when you run the app outside of the Simulator on an actual Apple TV. Please verify if that is also the case for you.

**Comment by cesarcarlos75** [comment]
I finally was able to get a USB-C to USB-A cable and tested on the Apple TV and yes the quality does look good on the device. Thanks!

**Comment by RikHeijdens** [comment]
I'm glad to hear that it plays fine on a regular device for you.
I'm closing this as it doesn't seem to be an issue on our end.
