### ISSUE TITLE
VMAP Not working

### ISSUE THREAD

**Issue by musictelevision** [jwplayer/jw-showcase-appletv#81]
Hi, 

We've joined the beta for the app with Ads. Our app looks great -- our branding, images, etc. are all loaded, our video playback is delivering dynamically, and we've already been approved for release by Apple. 

In order to release, based on our licensing, we have to include commercial breaks throughout playback -- we're looking to do so using the beta's VMAP feature. Our VMAP has been properly constructed (we've crossed checked by delivering ads to our Roku channel using the same VMAP), and our tag(s) deliver perfectly when injected into the app as a pre-roll. Are we missing a module? We're looking to get these VMAPs to deliver so we can release to the public.

**Comment by RikHeijdens** [comment]
Are you using the `adSchedule` property in `config.json`? If so, could you paste a copy of the VMAP here, or send us an email at support@jwplayer.com?

**Comment by musictelevision** [comment]
sure, see here thanks

"modules": [
    "https://tvos.jwpsrv.com/vast/current/vast.min.js"
  ],
  "vastTag": "",
  "adSchedule": "http://legendstvwebapp.azurewebsites.net/advertising/Apple_TV_VMAP_Schedule-2.xml",

**Comment by RikHeijdens** [comment]
I checked your VMAP, and I noticed that the URLs in the CDATA blocks appear to be invalid due to leading white space.

E.g. considering the following ad tag block:

```
<vmap:AdTagURI templateType="vast2">

        <![CDATA[ http://search.spotxchange.com/vast/2.0/85394?VPI=MP4&app%5bbundle%5d=REPLACE_ME&player_height=1080&player_width=1920&device%5bdevicetype%5d=7&device%5bmake%5d=Apple&device%5bmodel%5d=Apple%20TV&app%5bname%5d=REPLACE_ME&%20device%5bifa%5d=%25%ADVERTISING_IDENTIFIER_PLAIN%25%25
]]>
      </vmap:AdTagURI>
```

There is a single space between `![CDATA[` and `http://`, which makes this URL an invalid URL, and thus we can not load it using an XMLHttpRequest.

I artificially removed the whitespace, after I did that the ads started to play as expected.

**Comment by musictelevision** [comment]
You've got the magic touch. 

THANK YOU!
